### ISSUE TITLE
Bug in Search

### ISSUE THREAD

**Issue by milos-rakita** [inmagik/ionic-modal-select#101]
![searchproblem](https://user-images.githubusercontent.com/20794892/32550226-904c3bb2-c48c-11e7-9117-74b89d0034fe.gif)

**Comment by bianchimro** [comment]
hi @milos-rakita can you send me a codepen or something similar?
(the search should work)

**Comment by milos-rakita** [comment]
[image: Убаци слике 1]
At your page
https://inmagik.github.io/ionic-modal-select/#/app/examples-search first
example

2017-11-08 14:35 GMT+01:00 Mauro Bianchi <notifications@github.com>:

**Comment by milos-rakita** [comment]
At your site https://inmagik.github.io/ionic-modal-select/#/app/examples-search first Example at page.

**Comment by milos-rakita** [comment]
Why did you close this objection, if it is not corrected?

**Comment by bianchimro** [comment]
hey @milos-rakita... you close  the issue, not me.
