### ISSUE TITLE
Why both js and min js are in bower

### ISSUE THREAD

**Issue by Mavlarn** [inmagik/ionic-modal-select#12]
Now it is :
"main": [
    "dist/ionic-modal-select.js",
    "dist/ionic-modal-select.min.js"
  ],

I use wiredep, that setting causes the both js files are included in my index.html.

**Comment by bianchimro** [comment]
Sorry, I have not much experience about this.
What would you suggest to do?
Just keep the minified?

**Comment by Mavlarn** [comment]
In the normal, the non-minified version will be in main ja.
