### ISSUE TITLE
My on-select function can not get called

### ISSUE THREAD

**Issue by Mavlarn** [inmagik/ionic-modal-select#13]
I use the master code, but the on-select function is not called.

**Comment by bianchimro** [comment]
have you seen #6 ?

**Comment by Mavlarn** [comment]
Sorry.
Thanks.

**Comment by Mavlarn** [comment]
Sorry, another issue about this, It seems that the version 1.0.0 doesn't contain the support of 'on-select', could you release a new version for that?
Thanks.

**Comment by bianchimro** [comment]
@Mavlarn  You mean moving the tag v1.0.0 to another commit?
