### ISSUE TITLE
Two fancy selects on same page with search

### ISSUE THREAD

**Issue by arun0009** [inmagik/ionic-modal-select#14]
I was able to add 2 select drop downs on a single page. However, if I add the search functionality and search by text, the second dropdown shows only the options that matched the search text for first option in the drop down.

**Comment by arun0009** [comment]
I had to create 2 buttons with different scopes and it started working. If I use the same scope to display two drop downs it stores the entered text and only displays options matching that text. Also, is there a way to clear it? With 2 scope variables if I select different values and go back to select it has the entered select search and isn't clearing off on relaunch of select.

**Comment by bianchimro** [comment]
hi @arun0009 thanks for reporting. can you provide a codepen to show this problem?

**Comment by arun0009** [comment]
Hi @bianchimro thanks for your quick response & awesome repo! Absolutely love the fancy select functionality. 

Here the codepen: http://codepen.io/arun0009/pen/zrqavN?editors=101

What I'm trying to do is display quick times based on source and destination (which share the same stations). So I have two issues (first one i solved by using same array of select options by adding it to different scope variables sourceStations & destinationStations.

1. Do I have to create 2 different scopes for same select options?
2. Once I do a quick lookup, I want to clear the search text entered while selecting source and destination, or else when you try to select again on source/destination all you see is filtered select list.

Let me know if you need more details. Thanks!

**Comment by bianchimro** [comment]
@arun0009 glad you like this repo, thanks!

should be fixed in master, check this pen forked from yours:
http://codepen.io/bianchimro/pen/bEpZww?editors=101

Now you can avoid setting two different options array.

(Maybe we should provide an option to clear the search bar after an option if chosen.)
