### ISSUE TITLE
Newest version: It stopped working with delayed data

### ISSUE THREAD

**Issue by crissi** [inmagik/ionic-modal-select#16]
If the data for the ionic-modal-select is not populated right away, but is is populated later with an ajax call the modal is not showing anything.

This worked in an earlier build.

**Comment by crissi** [comment]
before the searchbar

**Comment by bianchimro** [comment]
@crissi  thanks for reporting.

can you provide a codepen or something tho show the issue?

**Comment by crissi** [comment]
http://codepen.io/anon/pen/qbqKLr?editors=101

The value that is set to start with is set, but it does not change if I set new content... Also tried to use angular.copy.

**Comment by bianchimro** [comment]
@crissi should be working now
