### ISSUE TITLE
Don't detect on-select changes when use reset button

### ISSUE THREAD

**Issue by svzosorio** [inmagik/ionic-modal-select#17]
I need a alternative for know when user reset the value but $scope.watch() or on-select does not work.

**Comment by bianchimro** [comment]
Hi @svzosorio
maybe we could add an explicit 'on-reset' callback for this case.

can you provide an example of what you need to sccomplish (for example a codepen) ?

**Comment by bianchimro** [comment]
@svzosorio Added `on-reset` callback. See if this helps with your use case.

**Comment by svzosorio** [comment]
Its perfect, whats is the support version for this feature?

**Comment by bianchimro** [comment]
Will be 1.2, still working in a couple of issues before making that release.
