### ISSUE TITLE
Selected value by default

### ISSUE THREAD

**Issue by AdrienDC** [inmagik/ionic-modal-select#22]
Hi, amazing job. 
Just a issue I have with a value I want to select by default, am I supposed to use selected-class ?
If yes, how to use it?

Thanks vm

**Comment by bianchimro** [comment]
hi,
I don't think we need an option for a default value, as you can just set the selected option by setting your model to the desired default.

Does this solve your problem ?

**Comment by AdrienDC** [comment]
hi @bianchimro ,
I'm not sure to have totally understood how to do it. In my view I have : 

``
<button class="button button-positive button-clear" modal-select ng-model="selectedCountry"  options="country" header-footer-class="bar-positive" has-search="false" modal-title="Select a country"
                sub-header-class="bar-calm"><b>
                    Country</b> {{selectedCountry}}
                    <div class="option">{{option}}</div>```

**Comment by bianchimro** [comment]
Ok, to provide a default selection, in your controller you can just do this to provide an initial selection (for example "Italy" ):
```
$scope.selectedCountry = 'Italy';
```

and your modal select will start with "Italy" selected (of course the option should be in your array)

If you want more help, consider providing a codepen or plunkr.

Closing this for now (not really an issue with the library), but let me know if you can implement your use case.

**Comment by AdrienDC** [comment]
Thanks a lot @bianchimro, I didn't realized it was that simple :+1:

**Comment by AdrienDC** [comment]
hi @bianchimro 

Actually, I have an issue with defining like this. I applied the default selected country like you suggested but afterward I needed to update my modelname to $scope.data.selectedCountry instead of $scope.selectedCountry.

By doing this, I am not able to set the default value anymore and got this error from my controller: error    TypeError: Cannot set property 'selectedCountry' of undefined

Any idea why?

**Comment by bianchimro** [comment]
> I needed to update my modelname to $scope.data.selectedCountry instead of $scope.selectedCountry.

mmh ... I don't understand why you had to do this.

difficult to help without seing the code. Can you post a codepen?

**Comment by AdrienDC** [comment]
yeah I had to do this in order to put back a default value of the modal select when my toggle is activated. Finally to solve this issue , I had to call a function in ng-init which initiate $scope.data.selectedCountry to my default value instead of doing it in the controller directly ... even if it's not recommended.
