### ISSUE TITLE
Additional delay in rendering data since 1.2

### ISSUE THREAD

**Issue by AdrienDC** [inmagik/ionic-modal-select#23]
Hi,
i noticed, there's a slight delay when rendering the select list since the v. 1.2

http://codepen.io/bianchimro/pen/epYYQO

Is it expected? Before 1.2, the list was showing smoothly.

Thanks

**Comment by bianchimro** [comment]
hi @AdrienDC , 
should be better now (in master branch, not in bower yet.)

this applies only to options rendered in "short list" mode
good catch, thanks!

**Comment by AdrienDC** [comment]
Thanks @bianchimro ! The behavior is really nice now :+1:
