### ISSUE TITLE
mousewheel

### ISSUE THREAD

**Issue by aldimol** [inmagik/ionic-modal-select#24]
mouse wheel does not work (scroll long list) in firefox

**Comment by bianchimro** [comment]
Hi @aldimol 
thanks for reporting.

Do you think this issue is related to this component or to ionic framework in general?

**Comment by aldimol** [comment]
to ionic framework in general

**Comment by bianchimro** [comment]
hi @aldimol 

Please refer to the ionic forum or ionic repo and issues on github for reporting this issue then.
(a good idea would be checking the issues first to see if someone else already reported this).

Ok, so I'm going to close this issue, as we cannot do a lot in the repo.

**Comment by bianchimro** [comment]
@aldimol  if you are interested in reopening, please provide a codepen with:

- a modal created directly with ionic **not shoiwing** the mousewheel issue
- a modal-select created with `modal-select` directive **showing** the issue.

thanks!

**Comment by aldimol** [comment]
The problem is not solved by the developer.
No time to wait for the decision, put factor 40 on the vertical scrolling.
         self.scrollBy (
           (e.wheelDeltaX || e.deltaX || 0) / self.options.wheelDampen,
           (-e.wheelDeltaY || e.deltaY * 40 || 0) / self.options.wheelDampen
         );
Sorry for my bad english
thanks!
