### ISSUE TITLE
Options to set search placeholder

### ISSUE THREAD

**Issue by redsoft7** [inmagik/ionic-modal-select#27]
There is not option to set the string for the search placeholder

**Comment by bianchimro** [comment]
fixed in master: you should be able to set the placeholder via `search-placeholder` attribute.

**Comment by redsoft7** [comment]
When the next repository tag is planned?

**Comment by bianchimro** [comment]
@redsoft7 
just released 1.3.0
(and dropped 1.2 as was not even registered in bower)

**Comment by redsoft7** [comment]
Thanks!
