### ISSUE TITLE
Selected value callback

### ISSUE THREAD

**Issue by fmendoza** [inmagik/ionic-modal-select#3]
Hi, great directive, just one question. If i want to do certain action when one of the options is selected, how can i do it? It seems i only have the option to manually watch the model.

**Comment by bianchimro** [comment]
You're right, there's no callback option right now.
I'll add this option, thanks for the idea!

I think the api will be something like

```
on-select="callback(newValue, oldValue)"
```

What do you think?

**Comment by bianchimro** [comment]
Added the option, still undocumented.

**Comment by fmendoza** [comment]
Just tested, it works :)

**Comment by bianchimro** [comment]
@fmendoza thanks for testing, closing issue.
