### ISSUE TITLE
Modal-Select layout issues - windows phone 8.1

### ISSUE THREAD

**Issue by flamed68** [inmagik/ionic-modal-select#32]
your plugin working perfectly on iOS and Android device. But, getting issues when adding for WP. modal-select options are not showing correctly. please see the attached image. 
![capture](https://cloud.githubusercontent.com/assets/2519754/13244470/6a05a41c-da2c-11e5-88e9-e683d09b7490.PNG)

**Comment by bianchimro** [comment]
Hi @flamed68 
i am very sorry but right now I have no chance to test it now on a windows phone or emulator to work to solve this problem.
If you feel so and want to help with this I'll be happy to accept PRs

**Comment by bianchimro** [comment]
Any news on this?

**Comment by bianchimro** [comment]
Closing for now @flamed68 feel free to reopen it if you have any feedback.
