### ISSUE TITLE
Bower registry not getting the most recent version

### ISSUE THREAD

**Issue by luiscvalmeida** [inmagik/ionic-modal-select#33]
Don't know if I'm doing this wrong, but I'm doing `bower install ionic-modal-select` and it downloads the the 1.1.2 version while I think it should download the 1.2 version.
I even tried to force to install the 1.2 but it couldn't find it.

```
$ bower install ionic-modal-select#1.2
bower not-cached    git://github.com/inmagik/ionic-modal-select.git#1.2
bower resolve       git://github.com/inmagik/ionic-modal-select.git#1.2
bower ENORESTARGET  No tag found that was able to satisfy 1.2

Additional error details:
Available versions in git://github.com/inmagik/ionic-modal-select.git: 1.1.2, 1.1.1, 1.1.0, 1.0.0
```

I decided to install it using the git url, pointing to the master branch, like so: 
`$ bower install https://github.com/inmagik/ionic-modal-select.git#master`

**Comment by bianchimro** [comment]
Hi @luiscvalmeida 
seems like I make some mess with releases.
I had to drop the 1.2 to fix thinks.
Now you should be able to download the 1.3.0 via bower.

let me know if it works, closing for now
