### ISSUE TITLE
options-expression with track by doesn't apply order

### ISSUE THREAD

**Issue by luiscvalmeida** [inmagik/ionic-modal-select#34]
Here: http://codepen.io/anon/pen/PNqvWE?editors=101

If you remove the `track by name.id` it orders just fine by the name. Using `track by` the ordering stops working.

**Comment by bianchimro** [comment]
hi @luiscvalmeida 

Just gave a quick, look, i think it should read

`options-expression="name in selectableNames  | orderBy:'name' track by name.id "`

(track by is **after** order by)


https://docs.angularjs.org/api/ng/directive/ngRepeat
> track by must always be the last expression:

This seems to fix ordering for me

**Comment by luiscvalmeida** [comment]
@bianchimro duh, sorry for this and thanks!

**Comment by bianchimro** [comment]
.. that's I mistake I make frequently too, that's why I catched id quickly ;)

regards
Mauro
