### ISSUE TITLE
Search on Firebase $id

### ISSUE THREAD

**Issue by AdrienDC** [inmagik/ionic-modal-select#41]
Hi,
I've a strange issue when loading data from firebase. Both example below are displaying the same but I need to use the first one.

If I do:
`                    <button ng-change="selectChange()" modal-select hide-reset="true options-expression="cit in city" header-footer-class="bar-positive" has-search="true" modal-title="In which city are you ?" sub-header-class="bar-calm">
                        <div class="option">{{option.$id}}</div>
                    </button>`

The search is not functioning.

While if I do:
`                    <button ng-change="selectChange()" modal-select hide-reset="true options-expression="cit in city" header-footer-class="bar-positive" has-search="true" modal-title="In which city are you ?" sub-header-class="bar-calm">
                        <div class="option">{{option.name}}</div>
                    </button>`

It's working! 
Any idea how I can make it work with $id has search criteria?

**Comment by bianchimro** [comment]
mmmh, that's strange, your code seems ok to me.
did you try using explicit string indexing, like: 
```
option['$id']
```
vs
```
option.$id
```

If you can provide some testing code I can work with, I can try and take a look.

**Comment by AdrienDC** [comment]
Hi @bianchimro ,
unfortunately I tried but without success...

I've created a codepen to illustrate my issue: http://codepen.io/AdrienDC/pen/Xdevag

thanks for your help

**Comment by AdrienDC** [comment]
even with oderBy: '$id' it doesn't change anything :(

**Comment by bianchimro** [comment]
hi @AdrienDC ,
don't really know why, but seems like adding the attribute
```
search-properties="['$id']"
``
to the directive does the trick. (you can also add other fields to the array if needed)
See: http://codepen.io/bianchimro/pen/LNeZjp?editors=1010

Not sure, but maybe is something related with how angular.$filter works internally.

If my solution works for you, a good idea would be mentioning this case in the readme and docs,
let me know so I can close this issue and open one related to docs.

**Comment by AdrienDC** [comment]
Thanks @bianchimro ! Indeed with the master branch and this propertie it's working like a charm ;)
Strange issue though..
I think a lot of Ionic users are into firebase so it would be a great idea to mention this case in the docs.

**Comment by bianchimro** [comment]
perfect, I'm going to close this and add an issue for docs.
I agree this is strange, would be worth investigating if it's a $filter related issue.
