### ISSUE TITLE
Create NPM package

### ISSUE THREAD

**Issue by jgerstle** [inmagik/ionic-modal-select#42]
We are currently only using npm and not bower. Can you please make an NPM package for this library in addition to the bower one?

**Comment by bianchimro** [comment]
Hi @jgerstle 
I'll take care of this ASAP,
Best regards

**Comment by bianchimro** [comment]
I'm going to publish to npm starting from version 1.4

**Comment by bianchimro** [comment]
published 1.3.1-alpha.0 to npm
