### ISSUE TITLE
Directive option with FireBase

### ISSUE THREAD

**Issue by marc-martinez** [inmagik/ionic-modal-select#47]
Hello,
If I use a firebase object, nothing is displayed on the modal but if the same variable is hardcoded, the modal display works fine.
Any idea ?

Thanks for your help,
Marc

HTML:
```
<button class="button button-positive" modal-select ng-model="selectedBoat" options="boats" modal-title="Search a boat"
    has-search="true" >
      Add a boat
      <div class="option">
        <span ng-bind-html="option.BoatName"></span>
        <small ng-bind-html="option.Immatriculation"></small>
      </div>
</button>
```

Controller with Dynamic Variable:
```
angular.module('App')
.controller('HandicappedCtrl', function ($scope,$http,$ionicModal,BOATS) {
$scope.selectedBoat = null;
$scope.boats = BOATS;

})
.factory("BOATS", function($firebaseArray) {
  var boatsRef = new Firebase("https://MYAPP.firebaseio.com/srs");
  return $firebaseArray(boatsRef);
})

```

Hardcoded variable:
```
$scope.boats = [ {
  "BoatName" : "Alivys",
  "CCR" : 328,
  "Classe" : "TCF3",
  "Club" : "SNMC",
  "Country" : "SUI",
  "FirstName" : "georges",
  "Immatriculation" : "VD 9081",
  "LastName" : "wagner",
  "MultiHull" : "Non",
  "NoSrs" : 365,
  "Region" : "ACVL",
  "SailNo" : 339,
  "Serie" : "Oui",
  "TCF" : 1.005,
  "Type" : "First Class 8"
}, {
  "BoatName" : "Joyeuse",
  "CCR" : 298,
  "Classe" : "TCF4",
  "Club" : "CVL",
  "Country" : "SUI",
  "FirstName" : "Gilles",
  "Immatriculation" : "VD 5557",
  "LastName" : "Favre",
  "MultiHull" : "Non",
  "NoSrs" : 418,
  "Region" : "ACVL",
  "SailNo" : 17,
  "Serie" : "Non",
  "TCF" : 0.998,
  "Type" : "6 m (ancienne jauge)"
}];
```

**Comment by bianchimro** [comment]
hi @marc-martinez 
have you seen #41 ?

**Comment by marc-martinez** [comment]
hi @bianchimro 
Yes. I tried to set the search-properties="['$id']" but without success.

By the way, my understanding of this porerty was to limit the search on the properties listed..and trying with the static code I am still searching on all attributes...but this is not my blocking point.

It may be a clue for you but with dynamic or static data, when reopening the modal list, the preselected istem is not shown...but this is also not a blocking point :-)

**Comment by bianchimro** [comment]
hey @marc-martinez ,
sorry about the issue,  can you set up a codepen or something I can use to debug against your problem?

Also what version/commit of this repo are you using?
I'm sorry but lately a lot of changes were made, with poor updates to docs and no release on bower for a while.

regards
Mauro

**Comment by marc-martinez** [comment]
Hello,
Sorry for the delay...I am working on this project once in a way...

I tried to setup a codepen but I am not able to "enable" the FireBase mechanism...http://codepen.io/MMAR/pen/XKMQmb
You may fork the CodePen and take a look...currently the codepen is working with some static data...but if you switch the model boats and boatss you should use the FireBase model.

Hope I am clear :-)

Regards,
Marc

**Comment by Stigelme** [comment]
+1. i would be also very interested how get data from firebase to ionic modal select.

**Comment by bianchimro** [comment]
Maybe this issue has something in common with #65

**Comment by bianchimro** [comment]
hi @marc-martinez I finally reviewed your pen,
it just lacks js assets and "firebase" module injection into the app.
see 
http://codepen.io/bianchimro/pen/LNeZjp?editors=1010

for a working example
