### ISSUE TITLE
options does not watch for array updates

### ISSUE THREAD

**Issue by swaheed2** [inmagik/ionic-modal-select#49]
The docs says: 

> The directive will watch for changes in this array and modify its options accordingly.

But look at this simple codepen. The modal doesn't update with the new array.

http://codepen.io/anon/pen/NNJOMW

Really want to use this directive, but need to get this working.

**Comment by swaheed2** [comment]
fix: https://github.com/inmagik/ionic-modal-select/pull/50

**Comment by bianchimro** [comment]
hi @swaheed2 and thanks for your work . I will review it as soon as possible.

best regards

**Comment by swaheed2** [comment]
did you get a change to review the pull request @bianchimro

**Comment by iveoteam** [comment]
Hey, when can we expect this to be active? I really want to use this plugin but this issue makes it unusable for me... thanks

**Comment by bianchimro** [comment]
@iveoteam don't really know when, if you want to try and use the pull request in your code you can do it just now.
