### ISSUE TITLE
option-getter not working

### ISSUE THREAD

**Issue by s1lviu** [inmagik/ionic-modal-select#5]
<p>Hello! <br>
I have :</p>

<p>JS</p>

<pre><code> $scope.selected = function(Name){
            console.log(Name);
        };
</code></pre>

<p>and HTML</p>

<pre><code>&lt;div class="item item-body" ng-if="items"&gt;
            &lt;button class="button button-dark" modal-select="" ng-model="selectedname"  option-getter="selected(Name)"
                    options="items"  modal-title="Alege locatia"&gt;
               Alege
                &lt;div class="option"&gt;
                    &lt;a ng-click="numeales=option.name" class="item item-thumbnail-left"&gt;
                        &lt;img ng-src="{{ option.picture }}"&gt;
                        &lt;h2&gt;{{option.name}}&lt;/h2&gt;
                    &lt;/a&gt;
                &lt;/div&gt;
            &lt;/button&gt;
        &lt;/div&gt;
        &lt;div ng-if="numeales" class="item"&gt;
           Selected option: {{selectedname}}
        &lt;/div&gt;
</code></pre>

<p>I have 3 elements in array, but when I click on select to open modal, console.log gives me 9 objects, and when I select an element, {{selectedname}} does not update.</p>

**Comment by bianchimro** [comment]
@s1lviu `option-getter`, if set to a function call, accepts a parameter callled `option` (the parameter name is important in this case, as per #5), as function is passed into scope with a reference (`&`)

**Comment by s1lviu** [comment]
I understand now. Thanks!
