### ISSUE TITLE
iPad rendering

### ISSUE THREAD

**Issue by AdrienDC** [inmagik/ionic-modal-select#52]
Hi, it seems on iPad, the max height and max width is capped to some values, thus the new view rendering all the select option is displayed smaller than the actual iPad size..
Any idea on how to remove those max values?

Thanks

**Comment by bianchimro** [comment]
hi @AdrienDC ,
thanks for reporting.
Is this happening within a cordova app or a web page?

**Comment by AdrienDC** [comment]
In fact, it's a bit specific, it's a cordova app launched with ionic view.

**Comment by AdrienDC** [comment]
The issue seems similar to when you launch on navigator. It's not full screen like on a phone. Maybe it's not an issue but I was surprise by this display when I launched on iPad.

**Comment by bianchimro** [comment]
@AdrienDC , can you send a screenshot?

**Comment by AdrienDC** [comment]
It's like on this codepen, http://codepen.io/meanme/pen/ONmGzW
the modal select page is not fullscreen

**Comment by bianchimro** [comment]
I think this is the normal ionic behavior, on big screens the modal is not full page.
can we close this?

**Comment by AdrienDC** [comment]
Ok then, I wasn't sure about it
