### ISSUE TITLE
ionic icon in modal select

### ISSUE THREAD

**Issue by AdrienDC** [inmagik/ionic-modal-select#53]
Hi, is that possible to have an icon list in ionic-modal-select? I want to create a list of activity, thus I'll associate one icon for each.

Thanks

**Comment by bianchimro** [comment]
ji @AdrienDC ,

this is probably already possible, but undocumented.
In fact you can totally override the template,
see this pen by @meanme 

http://codepen.io/meanme/pen/ONmGzW

I am sorry I did not have time to document these features.
Let me know if this can help

**Comment by AdrienDC** [comment]
Thanks @bianchimro ! Yes it's quite helpful to try implementing this )
