### ISSUE TITLE
Modal select opened from popup

### ISSUE THREAD

**Issue by AdrienDC** [inmagik/ionic-modal-select#55]
Hi,
I got a new issue today while I was trying to open a modal select view from a popup.. The view stay behind the popup meaning that I can still interact with it but the view is greyed and I was hopping the view to be forward..

This css trick didn't really help
`.popup-open .backdrop {
z-index: 11;
}`

**Comment by bianchimro** [comment]
mmh, interesting.
should the popup be closed before opening the select?

**Comment by AdrienDC** [comment]
No, it should stay open to fill one field in the popup...

**Comment by AdrienDC** [comment]
Actually, changing the z-index of a modal to 13 is solving the issue.
