### ISSUE TITLE
Unable to populate if the data is comming from webapi

### ISSUE THREAD

**Issue by RupenAnjaria** [inmagik/ionic-modal-select#56]
Hi, I have following code, to get data from api and then set in list.

`        $http.get(sharedProperties.getURLOfLanguagesWebAPI()).then(function (data) {

            allData = sharedProperties.convertXml2JSon(data.data);

            for (var i = 0; i < allData.OVRLookupData.Languages.length; i++) {
                $scope.languages.push({ "id": parseInt(allData.OVRLookupData.Languages[i].LanguageCode), "name": allData.OVRLookupData.Languages[i].Language });
            }

            $scope.loadingLangues = false;

        }, function (data) {
            console.log(data);
        });`

HTML is like:
`<label name="Language" class="item item-selectbox">
                    <span class="input-label" style="float:left">Select Language</span>
                    <button class="button button-dark button-outline icon-right ion-arrow-down-b"
                            modal-select ng-model="selectedValue"
                            options="languages"
                            on-select="languageChange(newValue)"
                            modal-title="Select Language">
                        {{ selectedValue.name || &apos;Select Language&apos;}}
                        <div class="option">{{option.name}}</div>
                    </button>
                </label>`

If I print in html like {{languages}} then I can see the values. However, the select box shows empty list.

Is it possible to populate values via api call?

**Comment by RupenAnjaria** [comment]
It's a bug: http://stackoverflow.com/questions/38125589/unable-to-update-scope-after-executing-get-call-from-http/38126400#38126400

**Comment by bianchimro** [comment]
hi @RupenAnjaria , does this work after #49  ?

**Comment by RupenAnjaria** [comment]
Yes, it is working now.

**Comment by bianchimro** [comment]
ok, closing this, thanks!
