### ISSUE TITLE
on-select returns undefined

### ISSUE THREAD

**Issue by s1lviu** [inmagik/ionic-modal-select#6]
<p>Hello! <br>
I have :</p>

<p>JS</p>

<pre><code> $scope.selected = function(New, Old){
            console.log(NeW + ' and ' + Old);
        };
</code></pre>

<p>and HTML</p>

<pre><code>&lt;div class="item item-body" ng-if="items"&gt;
            &lt;button class="button button-dark" modal-select="" ng-model="selectedname"  on-select="selected(New,Old)"
                    options="items"  modal-title="Alege locatia"&gt;
               Alege
                &lt;div class="option"&gt;
                    &lt;a ng-click="numeales=option.name" class="item item-thumbnail-left"&gt;
                        &lt;img ng-src="{{ option.picture }}"&gt;
                        &lt;h2&gt;{{option.name}}&lt;/h2&gt;
                    &lt;/a&gt;
                &lt;/div&gt;
            &lt;/button&gt;
        &lt;/div&gt;
        &lt;div ng-if="numeales" class="item"&gt;
           Selected option: {{selectedname}}
        &lt;/div&gt;
</code></pre>

<p>And I receiving undefined on function call. - both parameters</p>

**Comment by lupuandrei** [comment]
I solved the problem.
"function call with arguments newValue and oldValue". 

The parameter names are very important, "newValue" and "oldValue".

            <button class="button button-dark" modal-select="" ng-model="selectedname"  on-select="selected(newValue, oldValue)"
                    options="items"  modal-title="Alege locatia">
               Alege
                <div class="option">
                    <a ng-click="numeales=option.name" class="item item-thumbnail-left">
                        <img ng-src="{{ option.picture }}">
                        <h2>{{option.name}}</h2>
                    </a>
                </div>
            </button>

**Comment by s1lviu** [comment]
Merci, @lupuandrei !
Functioneaza acum. :+1: 
Dar option-getter tot imi face figuri: https://github.com/inmagik/ionic-modal-select/issues/5

**Comment by bianchimro** [comment]
so, closing this, @lupuandrei answered correctly.
@s1lviu thanks for the feedback, but plz write in english!
