### ISSUE TITLE
onClose event

### ISSUE THREAD

**Issue by maniolek** [inmagik/ionic-modal-select#60]
Is there any chance to add 'onClose' attribute which could support the event when closing a modal? Would be really great!

**Comment by bianchimro** [comment]
good idea, that should be easy to implement.
Can you specify your use case?
regards

Mauro

**Comment by maniolek** [comment]
I'm using $interval for requests to have some specifics data fields up-to-date. Because of refreshing records, I have to cancel that interval and invoke it again. I can use on-reset and on-select options to trigger interval again, I don't have that possibility when I close the modal.

**Comment by bianchimro** [comment]
I understand. Will work on this ASAP
