### ISSUE TITLE
modal.shown event not broadcasted

### ISSUE THREAD

**Issue by xloading** [inmagik/ionic-modal-select#62]
Hi!

First of all thanks a lot indeed for great plugin!

Within my application I face one minor issue with it but it is really critical for my app.
In my case modal-select is opened from button in navbar while in the view behind it there is native Google map present (https://github.com/mapsplugin/cordova-plugin-googlemaps):
![image](https://cloud.githubusercontent.com/assets/1406364/18338075/c89a1342-759e-11e6-96bf-f8f4b0aaa069.png)

In order to make opened modal scrollable I need to do the following call (otherwise the dragging/tapping will continue to interact with the map):
```
plugin.google.maps.Map.getMap(document.getElementById("map_canvas")).setClickable(false);
```

In theory this should be done on modal.shown event as per $ionicModal docs, however when I put the following piece of code in my main controller (on body element) the event doesn't get caught:
```
$scope.$on('modal.shown', function() {
    console.log('Modal shown - mainCtrl!');
  });
```

I'm not a pro of AngularJS therefore I suppose myself to be missing something related to scopes etc (I've checked - watching on $rootScope doesn't resolve this either).

Could you please advise me whether it is possible to watch modal.shown event on modal-select and what could go wrong in my case?

I suppose the next challenge will be to get map clickable again after the modal is closed no matter whether this happened with select or cancel. Is it possible to watch modal.hidden as well?

Thanks a lot in advance!

**Comment by bianchimro** [comment]
Hi @xloading,
i'd try to use this feature of ionic:

http://ionicframework.com/docs/api/page/tap/

Instead of doing this:

```
plugin.google.maps.Map.getMap(document.getElementById("map_canvas")).setClickable(false);
```

You should do:

```
<div id="map_canvas" data-tap-disabled="true" >

</div>
```
if that does not work, try and wrap your div with another div, and apply the `data-tap-disabled` there instead.
Not sure, but this could solve  your issue.

Let me know if this works!
regards

Mauro

**Comment by xloading** [comment]
Hi Mauro!
Thanks for quick support, really appreciate this.

But I'm not sure that your advice indeed relates to my problem, though I have still tried to implement data-tap-disabled but it didn't work as required.

Let me clarify a bit - the problem in my case is that when Modal-Select is opened google maps native view is still active:
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#how-does-the-plugin-work
And that's why I have to use this call:
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#mapsetclickable

I utilize this call successfully when opening Ionic popups and this works fine, but in case of Modal-Select it seems I don't have any control over model showing-hiding events. Or is it still possible somehow?

Thank you!

Regards,
Georgy

**Comment by bianchimro** [comment]
Hi George,
I understand better your problem now, you are perfectly right.

To make this work, we should probably add this feature: #60 
so you can do the same on the close event.
I'm a bit busy right now, but I'd like to fix #60 asap as it should be really easy to implement it.
I cannot guarantee but I'll try to do it this week.
You have a deadline on your app?

**Comment by xloading** [comment]
Hi Mauro,
That's exactly what I was thinking about today - but it looks both onOpen and onClose attributes are required, strange that I have missed #60 earlier.

I'm working on my own startup app therefore no strict deadlines but it would be great if this can be enhanced within a week or so.
Would be glad to help you but I don't have any experience with Angular directives at all yet. Still will try to understand your code better, I'm sure this will help me someday.

Thanks!

**Comment by bianchimro** [comment]
Hi, just pushed a new version with the on-close callback,
that gets fired when modal is closes (in any way).

Let me know if it works for your use case.
Regards

Mauro

**Comment by bianchimro** [comment]
Hi, any feedback on this?
I just merged a pull request that solves a problem for the "on-close" callback.
Try with the new release.

**Comment by bianchimro** [comment]
should be closable, please @xloading reopen it if it's the case.

**Comment by xloading** [comment]
Hi Mauro!

Apologies for late response, I was on vacations with rare internet connection.
I have checked the part related to on-close and it seems to work well indeed, thank you! But if you look once again at my original comments you can notice that my primary intention was to have the on-open callback feature.

Therefore I have proceeded with forking and minor additional change to cover this case as well:
https://github.com/xloading/ionic-modal-select/commit/b872b53d93cb3ac1bd907796352e7464ffe24ee9

It worked like a charm: both onOpen and onClose callbacks are executed perfectly. However I still have a couple of questions:
1. To be honest I didn't get the purpose of code with hiddenCb variable. Could you please briefly explain what was it added for?
2. Also I didn't get what happened to this PR commit: https://github.com/inmagik/ionic-modal-select/commit/62cf5cad9df02712d1e0e1d7a1b2796629f89be1
It seems it is absent in current version of src/ionic-modal-select.js and still everything is working fine.

Thank you in advance!

**Comment by bianchimro** [comment]
hi George,

you are right, sorry for misunderstanding, you need "on-open".

> Therefore I have proceeded with forking and minor additional change to cover this case as well:
> xloading@b872b53
> 

seen your fork and opened a pr myself, this feature is interesting. will merge it asap.


> 1. To be honest I didn't get the purpose of code with hiddenCb variable. Could you please briefly explain what was it added for?

It's used to do something when the modal is dismissed, either by picking a value, resetting, or just closing the modal. It's bound tho the original modal.hidden ionic event.

> 2. Also I didn't get what happened to this PR commit: 62cf5ca

I analized the code better and that was a regression, that commit was not needed.
If you use the `on-close` attribute be sure to pass in a **function** and not a **function call** as this is passed by reference and not by value. (it will be called by the directive)

best regards
Mauro
