### ISSUE TITLE
Callback function before the modal select

### ISSUE THREAD

**Issue by gopi014** [inmagik/ionic-modal-select#73]
I have a button as modal select and three input fields above that.On click of the button first I need to validate if all the three input fields are filled in and the modal select should open only if all the three fields has values.There is a callback method on-select which calls after the modal select is selected.But I need a callback function to validate the fields before .Any methods available currently or is there an way to trigger the modal select programmatically.

**Comment by bianchimro** [comment]
hi,
I think you should leverage `ng-disabled` for disabling the button until the validation is fine.
External validation is not in the roadmap.

regards
Mauro

Mauro
