### ISSUE TITLE
Its possible group by the select values?

### ISSUE THREAD

**Issue by iosdroid** [inmagik/ionic-modal-select#74]
select values group by some value its not working

**Comment by bianchimro** [comment]
hi,
can you post an example?

**Comment by iosdroid** [comment]
Hi I have a array like 
 $scope.players = [
      {id:'1',name: 'Gene', team: 'alpha'},
      {id:'2',name: 'George', team: 'alpha'},
      {id:'3',name: 'Steve', team: 'beta'},
      {id:'4',name: 'Paula', team: 'beta'},
      {id:'5',name: 'Scruath', team: 'gamma'}
    ];


I want to show the select like
**albha**
 

- Gene

- George

**beta**

- Steve

- Paula

**gamma**

- Scruath

**Comment by bianchimro** [comment]
Hi you can pass in a custom template, but it's not (yet) documented.
see this codepen for an example of template customization:

http://codepen.io/meanme/pen/ONmGzW

**Comment by iosdroid** [comment]
I am in little confusion. can u create custom templates for my examples?

**Comment by bianchimro** [comment]
sorry but I am quite busy at the moment.
If you are not in a hurry I will help ASAP.
Maybe you can setup a codepen so that i can edit it?

**Comment by iosdroid** [comment]
No Issues..I am Wait for your example
