### ISSUE TITLE
Can't use the module

### ISSUE THREAD

**Issue by brunocollaco** [inmagik/ionic-modal-select#78]
Heya!

I just clone the repo, copied <code><script src='js/ionic-modal-select.js'></script></code> and added it to my index.html, as you can see.

Also have it declared here:
<code>angular.module('starter', ['ionic', 'starter.controllers', 'starter.services','anguFixedHeaderTable', 'ionic-modal-select'])</code>

Then I made a controller like the example in http://codepen.io/bianchimro/pen/epYYQO?editors=1010
and tried to call it inside ion-content.

I'm getting this: 
![screen shot 2016-11-14 at 2 29 20 pm](https://cloud.githubusercontent.com/assets/2163579/20272998/deb2f75e-aa76-11e6-9912-7dd40a0b7584.png)

What am I doing wrong? 
Sorry cuz I'm newbie and thx a lot in advance.

**Comment by bianchimro** [comment]
hey,
if you clone the repo you should use the js file found in the "dist" folder, seems like you're using the `src` one. 

Let me know if this does this fix your problem.

regards
Mauro

**Comment by brunocollaco** [comment]
Yaaaaay!

It worked! Thanks a lot man!
