### ISSUE TITLE
the compare with selected option failed if options is an object

### ISSUE THREAD

**Issue by ulion** [inmagik/ionic-modal-select#8]
getSelectedValue(option) == ui.value

the above compare will never return true if ui.value is the object which is same with the option (but obviously the object compare doesn't return true for some reason)

**Comment by bianchimro** [comment]
@ulion thanks for reporting.

can you provide a plunkr or codepen to show the issue?
Everything seems fine in the demo:

http://codepen.io/bianchimro/pen/epYYQO?editors=101

**Comment by ulion** [comment]
that happened when you saved the select option, but reload the page again,
e.g. load from saved data, you have a saved object, it has same content as
the one in the option list, but it's different object.

that means, current implement can not judge they are the same object, or
should be treat as same. maybe, we just need to support user can setup a
function, which take 2 option values then compare them tell whether it's
same.

2015-11-05 18:40 GMT+08:00 Mauro Bianchi <notifications@github.com>:

> @ulion <https://github.com/ulion> thanks for reporting.
>
> can you provide a plunkr or codepen to show the issue?
> Everything seems fine in the demo:
>
> http://codepen.io/bianchimro/pen/epYYQO?editors=101
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inmagik/ionic-modal-select/issues/8#issuecomment-154025740>
> .
>



-- 
Ulion

**Comment by bianchimro** [comment]
@ulion can you provide a codepen where data is saved and loaded from localstorage so we can use it to test against this issue?
thanks

**Comment by ulion** [comment]
http://codepen.io/anon/pen/EPZmyq


2016-01-02 21:45 GMT+08:00 Mauro Bianchi <notifications@github.com>:

> @ulion <https://github.com/ulion> can you provide a codepen where data is
> saved and loaded from localstorage so we can use it to test against this
> issue?
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inmagik/ionic-modal-select/issues/8#issuecomment-168394130>
> .
>



-- 
Ulion

**Comment by bianchimro** [comment]
@ulion thanks for the codepen
should be fixed now.
