### ISSUE TITLE
Subheader & footer

### ISSUE THREAD

**Issue by ThapeloDev** [inmagik/ionic-modal-select#80]
Hello, this might be an incorrect platform to address such...

I am having a problem where my clear, cancel and reset buttons don't get displayed appropriately.
I have added ionic-modal to get a few options and list them... but however i cannot seem to center or manipulate the width of the modal to include all other items to be displayed well. 

Please see the below screen dump... I have also indicated with elements don't get displayed well

![image](https://cloud.githubusercontent.com/assets/13315435/20751558/0e514732-b705-11e6-95aa-c17cffb685ac.png)

Thank you...
EnergesP

**Comment by bianchimro** [comment]
hi @ThapeloDev , which platform are you developing for?

**Comment by mino922** [comment]
Was there ever any update on this? I'm experiencing the same issue. 

Also, I was wondering if it was possible to replace the buttons (cancel, reset, etc) and just use text.
