### ISSUE TITLE
option render problem

### ISSUE THREAD

**Issue by ulion** [inmagik/ionic-modal-select#9]
yes, we can use

```
<div class="option">
  {{option}}
</div>

or

<div class="option">
  {{option.propertyName}}
</div>
```

But, when I try this:

```
<div class="option">
  {{theScopeFunction(option)}}
</div>
```

the function always got undefined as the parameter.

**Comment by bianchimro** [comment]
The directive has a private scope so your function does not get found.
I don't plan to change this design right now, but you can bypass this restriction by calling that function directly on your controller on options before passing them to the directive
Not sure if it's right design but It makes more sense to me.
